# Generated by Django 4.2.7 on 2023-11-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDetails',
            fields=[
                ('AdminId', models.AutoField(primary_key=True, serialize=False)),
                ('AdminName', models.CharField(max_length=500)),
                ('AdminPass', models.CharField(max_length=50)),
            ],
        ),
    ]
