# Generated by Django 4.2.7 on 2023-11-06 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0002_admindetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdetails',
            name='BoughtProperties',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersdetails',
            name='PostedProperties',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersdetails',
            name='RentedProperties',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersdetails',
            name='WishListed',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('propertyId', models.AutoField(primary_key=True, serialize=False)),
                ('selling_type', models.CharField(choices=[('Buy', 'Buy'), ('Rent', 'Rent')], max_length=10)),
                ('coast', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('emi', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('location', models.CharField(max_length=500)),
                ('property_type', models.CharField(max_length=100)),
                ('deal_made', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.usersdetails')),
            ],
        ),
    ]
