# Generated by Django 4.2.7 on 2023-11-13 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0003_alter_usersdetails_boughtproperties_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.properties')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.usersdetails')),
            ],
        ),
    ]
