# Generated by Django 4.2.7 on 2023-11-14 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0004_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='reports',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_reports', to='realestate.properties')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.usersdetails')),
            ],
        ),
    ]
