# Generated by Django 4.2.7 on 2023-11-16 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDetails',
            fields=[
                ('AdminId', models.AutoField(primary_key=True, serialize=False)),
                ('AdminName', models.CharField(max_length=500)),
                ('AdminPass', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('propertyId', models.AutoField(primary_key=True, serialize=False)),
                ('selling_type', models.CharField(choices=[('Buy', 'Buy'), ('Rent', 'Rent')], max_length=10)),
                ('coast', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('emi', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('location', models.CharField(max_length=500)),
                ('property_type', models.CharField(max_length=100)),
                ('deal_made', models.BooleanField(default=False)),
                ('reports', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UsersDetails',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=500)),
                ('UserMail', models.EmailField(max_length=500, unique=True)),
                ('UserPassword', models.CharField(max_length=50)),
                ('PostedProperties', models.IntegerField(default=0)),
                ('RentedProperties', models.IntegerField(default=0)),
                ('BoughtProperties', models.IntegerField(default=0)),
                ('WishListed', models.IntegerField(default=0)),
                ('otpvalidation', models.CharField(default=0, max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brokers.properties')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brokers.usersdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_reports', to='brokers.properties')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brokers.usersdetails')),
            ],
        ),
        migrations.AddField(
            model_name='properties',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brokers.usersdetails'),
        ),
    ]
