# Generated by Django 4.2.7 on 2023-11-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindetails',
            name='otpvalidation',
            field=models.CharField(default=0, max_length=6),
        ),
    ]
